version: "3.7"
services:
  database:
    image: "postgres"
    env_file:
      - .env
    network_mode: "host"
  blog_backend:
    build: .
    env_file:
      - .env
    network_mode: "host"
    depends_on:
      - "database"
    command: bash -c "./wait-for-it.sh --host=localhost --port=5432 --timeout=60 && /app/src/main"
